spring:
  application:
    name: FitTools
  datasource:
    url: jdbc:mysql://localhost:2345/fittools
    username: root
    password: 123456
  redis:
      host: localhost
      port: 6379
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
jwt:
  signatureKey: "Echo 42"